import React,{useState}from'react';import{createRoot}from'react-dom/client';import{createPortal}from'react-dom';import{ArrowLeft,ArrowRight,BellRing,Check,ChevronDown,ClipboardCheck,FileLock2,Mail,Menu,MessageCircleMore,RefreshCw,Route,ShieldCheck,Target,TimerReset,UsersRound,Volume2,VolumeX,X}from'lucide-react';import'./styles.css';
const A='/assets/';
const tabs=['The signal','Feedback loop','Four-part cycle','Loop patterns','Guardrails','Exam lens'];
const cycle=[
['Send','06-send.png','Puts the communication out through whichever method fits the message.'],
['Acknowledge','07-acknowledge.png','Expected within a specific timeframe, stated directly in the communication plan itself — not left vague as “please respond when convenient,” but a defined, agreed window.'],
['Feedback','08-feedback.png','Here’s the trap worth naming precisely: acknowledgment is not understanding. A stakeholder replying “got it” confirms the message arrived — it says nothing about whether they actually understood it, agreed with it, or intend to act on it. Feedback is what actually tests understanding, surfacing whether the message landed the way it was meant to.'],
['Adjust','09-adjust.png','Closes the loop — the communication approach itself gets refined based on what the feedback reveals, rather than repeating an approach that isn’t actually working.']];
const patterns=[
['The Pulse Check','11-pulse.png','A short, two-question check sent after a stakeholder briefing, with responses tracked and trended on a dashboard over time — giving a running signal of whether sentiment is actually improving or stagnant, rather than relying on one impression from a single meeting.'],
['“Decisions Needed” Section','12-decisions.png','Built into a steering committee or sponsor-level report, specifically designed to force an actual response by a defined cadence — where silence gets escalated, not quietly read as tacit consent.'],
['Retrospectives as an Internal Loop','13-retrospective.png','Asking the team directly, “what didn’t you hear about in time?” — surfacing communication gaps the team actually experienced, not just the ones the project manager assumed didn’t exist.'],
['Vendor SLA Acknowledgment','14-vendor.png','Required acknowledgment-of-receipt on vendor SLA-related communications, tied to a defined responsiveness KPI — so a vendor’s silence on a critical notice is itself flagged rather than assumed to mean nothing was wrong.']];
const guards=[
['Escalation Processes','16-escalation.png','Treat silence as data, not passive agreement. A missed acknowledgment triggers a direct follow-up through another channel. An unanswered decision gets explicitly named in the next status report. A pending decision creating real schedule exposure goes to the sponsor, with the cost of continued delay stated plainly. A cross-organizational deadlock gets escalated to steering rather than left to fester.'],
['Named Authority Over Confidential Release','17-authority.png','Exactly who is authorized to release which category of sensitive information, paired with clear channel rules (certain sensitive data never travels over email or chat, full stop) and any constraints from specific legislation or regulation. Written down as plan content, not carried as tribal knowledge tied to one person.'],
['The Plan Evolves by Design','18-evolution.png','A defined method for updating and refining the communication plan as the project progresses is itself a plan component — particularly important when the stakeholder community changes meaningfully between phases. A refresh trigger set at a specific milestone — say, a pilot phase gate where a whole new group of stakeholders joins — ensures the entire communication grid gets re-analyzed at that point, rather than silently going stale.']];
const reveal={
hook:{title:'The Signal Is Only the Start',image:'02-hook-modal.png',text:'Project communication needs the same discipline. Sending a message isn’t the finish line — sending only proves distribution, never understanding. This lesson is about closing that gap deliberately, building a feedback loop into the communication plan itself, and treating silence as a signal to act on rather than a comfortable assumption of agreement.'},
enabler:{title:'Establish a Feedback Loop',image:'04-enabler-modal.png',text:'This enabler — ECO Process Task 8.3 — asks the project manager to establish a feedback loop. Feedback is information about reactions to communications, a deliverable, or a situation — supporting genuine interactive communication among the project manager, the team, and every other stakeholder. Establishing this loop is a named, explicit duty, not something left to happen informally or hoped for.'},
exam:{title:'Establish a Feedback Loop',image:'20-exam-modal.png',text:'Establishing a feedback loop means designing it deliberately into the communication plan itself — send, acknowledge, feedback, adjust — with acknowledgment expected within a stated timeframe, and genuine understanding tested through real feedback rather than assumed the moment a message is confirmed received. Escalation processes treat missed responses as data demanding action, named authority governs who can release confidential information and through which channels, and the plan itself is built to evolve — refreshed at defined trigger points as the stakeholder community changes. A feedback loop that isn’t designed this way doesn’t fail loudly. It fails quietly — in the gap between acknowledgment and actual understanding, where silence gets mistaken for agreement until the moment it turns out it never was.',bullets:['Four-part cycle: send, acknowledge, feedback, adjust — acknowledgment ≠ understanding','Feedback patterns should fit the audience: pulse checks, “decisions needed” sections, retrospectives, vendor SLA acknowledgment','Escalation treats silence as data — missed acknowledgment triggers direct follow-up or explicit naming, never silent assumed approval','Named authority for confidential release and a defined plan-refresh trigger are both explicit, written plan components, not informal practice']}};
const quiz={q:'Scenario: A project’s steering committee report includes a “decisions needed” section requesting sign-off on a scope change by a stated deadline. The deadline passes with no response from the committee, and the project manager proceeds with the original scope, treating the silence as implicit approval. What does this scenario illustrate?',a:['The escalation process failed — a missed acknowledgment on a decision like this should have triggered a direct follow-up or been named explicitly in the next report, rather than being read as approval','This is correct — silence after a clearly stated deadline should reasonably be treated as approval','The project manager should have used push communication instead of an interactive report format','This is a stakeholder engagement problem that should be resolved through a communication styles assessment'],good:'Correct! This is precisely the gap this lesson is built around. A missed acknowledgment on a genuine decision point should trigger escalation — a direct channel, or explicit naming in the next status report — not a silent assumption that no response means yes.',bad:'Reconsider — this is exactly the assumption a well-designed feedback loop is built to prevent; the delivery method wasn’t the issue, and this is a structural escalation gap, not a communication-style mismatch.'};
function Modal({d,close,read}){const[step,setStep]=useState(0);return createPortal(<div className="modal-backdrop" onClick={close}><section className="focus-modal" onClick={e=>e.stopPropagation()}><button className="modal-x" aria-label="Close" onClick={close}><X/></button>{step===0?<><img className="modal-illustration" src={A+d.image}/><h3>{d.title}</h3><div className="modal-copy"><p>{d.text}</p></div></>:<div className="memory-step"><p className="eyebrow">EXAM-RELEVANT ENABLERS TO REMEMBER</p><ul>{d.bullets.map(x=><li key={x}>{x}</li>)}</ul></div>}{d.bullets&&step===0?<button className="modal-action" onClick={()=>setStep(1)}>Next <ArrowRight/></button>:<button className="modal-action" onClick={()=>{read();close()}}>Mark as read <Check/></button>}</section></div>,document.body)}
function Quiz({finish}){const[p,setP]=useState(null);return createPortal(<div className="knowledge-backdrop"><section className="knowledge-modal"><p className="quiz-label"><Target/> MICRO KNOWLEDGE CHECK</p><h3>{quiz.q}</h3><div className="answers vertical">{quiz.a.map((x,i)=><button key={x} onClick={()=>setP(i)} className={p===i?(i===0?'correct':'wrong'):''}><span>{'ABCD'[i]}</span>{x}</button>)}</div>{p!==null&&<><p className={`feedback ${p===0?'good':'bad'}`}>{p===0?quiz.good:quiz.bad}</p><button className="finish-check" onClick={finish}>Finish check <ArrowRight/></button></>}</section></div>,document.body)}
function CardIcon({group,index}){const sets={cycle:[Mail,ClipboardCheck,MessageCircleMore,RefreshCw],patterns:[TimerReset,ClipboardCheck,UsersRound,BellRing],guards:[Route,FileLock2,ShieldCheck]},Icon=sets[group][index];return <span className="direct-card-icon"><Icon/></span>}
function App(){const[s,setS]=useState(0),[done,setDone]=useState(Array(6).fill(false)),[modal,setModal]=useState(),[seen,setSeen]=useState({}),[quizOpen,setQuizOpen]=useState(false),[sound,setSound]=useState(true);const mark=i=>setDone(v=>v.map((x,n)=>n===i?true:x)),go=i=>{if(i>=0&&i<6&&(i===0||done[i-1]))setS(i)},open=(group,i,item)=>setModal({title:item[0],image:item[1],text:item[2],group,index:i,detail:true}),read=()=>{if(modal.detail){const key=`${modal.group}-${modal.index}`,next={...seen,[key]:true};setSeen(next);const needed=modal.group==='cycle'?4:modal.group==='patterns'?4:3;if(Object.keys(next).filter(k=>k.startsWith(modal.group+'-')).length===needed&&modal.group!=='guards')mark(s)}else mark(s)};const hero=(title,body,img,d,label,ey)=><section className="hero"><div>{ey&&<p className="eyebrow">{ey}</p>}<h2>{title}</h2><p>{body}</p><button className="primary" onClick={()=>setModal(d)}>{label} <ArrowRight/></button></div><img src={A+img}/></section>;const cards=(items,group,title,body)=><section className="components"><h2>{title}</h2><p>{body}</p><div className={`direct-card-grid count-${items.length}`}>{items.map((x,i)=>{const read=seen[`${group}-${i}`];return <button key={x[0]} onClick={()=>open(group,i,x)} className={`direct-detail-card ${read?'visited':''}`}><CardIcon group={group} index={i}/><span className="direct-card-copy"><small>{read?<><Check/> READ</>:String(i+1).padStart(2,'0')}</small><strong>{x[0]}</strong></span><ArrowRight className="direct-card-arrow"/></button>})}</div>{items.every((_,i)=>seen[`${group}-${i}`])&&group!=='guards'&&<p className="interaction-complete"><Check/> Interaction complete — continue when ready.</p>}{group==='guards'&&items.every((_,i)=>seen[`${group}-${i}`])&&<button className="knowledge-cta centered" onClick={()=>setQuizOpen(true)}><Target/> Start knowledge check <ArrowRight/></button>}</section>;return <div className="app"><header><button className="course"><Menu/> Project Management Professional <ChevronDown/></button><div className="dots">{Array.from({length:10},(_,i)=><span key={i} className={i<9?'past':i===9?'current':''}>{i<9&&<Check/>}</span>)}</div><div className="tools"><button onClick={()=>setSound(!sound)}>{sound?<Volume2/>:<VolumeX/>}{sound?'Sound on':'Sound off'}</button><button>Quit</button></div></header><div className="lesson-frame"><div className="section-label">SECTION {s+1} OF 6</div><nav style={{gridTemplateColumns:'repeat(6,1fr)'}}>{tabs.map((t,i)=><button key={t} onClick={()=>go(i)} disabled={i>0&&!done[i-1]} className={i===s?'active':done[i]?'complete':''}>{done[i]&&<Check/>}{t}</button>)}</nav><main>
{s===0&&<section className="hero"><div><p className="eyebrow">LESSON 4.10.3</p><h1>Establish a<br/>Feedback Loop</h1><p>A smoke detector that beeps once, and then stops regardless of whether anyone actually got up to check it, isn’t really an alarm system. A real safety system doesn’t just send the signal — it confirms someone received it, and it escalates when nobody responds. Silence isn’t treated as “fine.” It’s treated as data demanding a next step.</p><button className="primary" onClick={()=>setModal(reveal.hook)}>Reveal the communication discipline <ArrowRight/></button></div><img src={A+'01-hook.png'}/></section>}
{s===1&&hero('What This Enabler Asks','This enabler makes something explicit that too often gets left to happen informally, or just hoped for.','03-enabler.png',reveal.enabler,'Reveal the enabler')}
{s===2&&cards(cycle,'cycle','Designing the Loop: A Four-Part Cycle','The design borrows the interactive communication model’s steps and turns them into something operational and enforceable. Click each part to explore.')}
{s===3&&cards(patterns,'patterns','Feedback Loop Patterns','Feedback loops should be shaped to fit their specific audience, not applied as one generic template everywhere. Click each pattern to explore.')}
{s===4&&cards(guards,'guards','Escalation, Control, and Evolution','Two further guard-rails belong in the communication plan as explicit, written components — not as informal practice everyone is expected to intuit. Click each to explore.')}
{s===5&&hero('Back to that smoke detector one more time —','because the difference was never about whether the alarm made noise. It was about what happened after.', '19-exam.png',reveal.exam,'Reveal the exam lens','EXAM LENS')}
</main><footer><button onClick={()=>go(s-1)} disabled={!s}><ArrowLeft/> Previous</button><button className="continue" onClick={()=>go(s+1)} disabled={!done[s]}>{s===5?'Complete':'Continue'} <ArrowRight/></button></footer></div>{modal&&<Modal d={modal} close={()=>setModal()} read={read}/>} {quizOpen&&<Quiz finish={()=>{setQuizOpen(false);mark(4)}}/>}</div>};createRoot(document.getElementById('root')).render(<App/>);
